### PR TITLE
Change replacing '@theia/plugin' to 'theia.<frontendModuleName>'

### PR DESCRIPTION
**Pull request by evidolob**
theia-ide/theia#2708
Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
what will happen on existing frontend plugins ?

**Comment by evidolob** [comment]
Unfortunately they will not work

**Comment by benoitf** [comment]
can we still provide a dummy theia object for a while ?

**Comment by evidolob** [comment]
We can, only if `@theia/plugin": "theia.<%= params.frontendModuleName %>` we change to for example   `@theia/plugin": "theiaAPI.<%= params.frontendModuleName %>` and provide global var `theia` with dummy plugin

**Comment by benoitf** [comment]
I mean yes here we keep the change there but in theia core we also bind a theia object for some time

**Comment by evidolob** [comment]
Previously we have `theia` object in global scope, in https://github.com/theia-ide/theia/pull/2764 pull I place `theia` object as proxy object and methods of this object will return api object per plugin.
If we wont to keep working existing plugins we need change name of global object in this pull:
`theia.< frontendModuleName >` to `theiaAPI.< frontendModuleName >` or some other name

**Comment by benoitf** [comment]
ok let's keep it like this for now

**Comment by benoitf** [comment]
I mean, go ahead and modify maybe https://github.com/theia-demo-plugins/theia-frontend-plugin ?

**Comment by evidolob** [comment]
Done: https://github.com/theia-demo-plugins/theia-frontend-plugin/pull/15

**Comment by evidolob** [comment]
Depends on: https://github.com/theia-ide/theia/pull/2764

**Pull request merged**
