### PR TITLE
Ensure code is formatted, linter, etc.

### PR DESCRIPTION
**Pull request by benoitf**
update as well typescript version

CQs:
- [x] TypeScript v2.9.2 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16945
- [x] Tslint v5.10.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16944
- [x] typescript-formatter v7.2.2 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16943

Change-Id: I6763c492eb313591c16648797c16d7eb23cc30f3
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>

### CODE REVIEW

**Review by evidolob — APPROVED** [review]

**Review by azatsarynnyy — APPROVED** [review]
I think it'd be useful to have the similar configurations set up for the plugin template as well. So each generated plugin will have the same formatting/linter rules, etc.

**Comment by benoitf** [comment]
@azatsarynnyy agreed. I was thinking the same. 
I don't know if it's possible to host rules somewhere so if we update rules it can update globally (like based on @theia/plugin version)

**Comment by benoitf** [comment]
https://palantir.github.io/tslint/2016/03/31/sharable-configurations-rules.html may be a starting point

**Comment by benoitf** [comment]
I will try and provide separate PR for adding linter, etc in plugins themselves

**Pull request merged**
