### PR TITLE
adjust packager call to latest fix for windows run

### PR DESCRIPTION
**Pull request by amiramw**
Signed-off-by: Amiram Wingarten <amiramw@gmail.com>

### CODE REVIEW

**Comment by benoitf** [comment]
hello @amiramw , somehow it seems there is an error on ip validation

**Comment by benoitf** [comment]
it looks like signed off is different of the committer email

**Comment by amiramw** [comment]
Fixed it

**Comment by benoitf** [comment]
thanks

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
CI was OK, merging !
thanks for the patch @amiramw

**Pull request merged**
